export const availableTimes = {
  "2024-07-28": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: true,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: true,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-07-29": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: true,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-07-30": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-07-31": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-08-01": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-08-02": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-08-03": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-08-04": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
  "2024-08-05": [
    {
      time: "4:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "4:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "5:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "6:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "7:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "8:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:00 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
    {
      time: "9:30 P.M.",
      diners: 0,
      occasion: "None",
      specialRequests: "None",
      booked: false,
      reservationFName: "None",
      reservationLName: "None",
      reservationEmail: "None",
      reservationPhoneNum: "None",
      reservationID: "None",
    },
  ],
};
